
/**** Generated by LSwriteSrcFile (mode=+1).
   Ready to #include from samples/c/ex_src ****/


{ // begin LP data
//////// Model sizes, objective sense and constant
  int    errorcode = 0;
  int    nCons     = 5;
  int    nVars     = 7;
  int    dObjSense = LS_MAX;
  double dObjConst = 0;
//////// Objective coefficients
  double padC[] =
  {
    0, 0, 0, 0, 0, 0,
    1, -1.0
  };

//////// RHS values
  double padB[] =
  {
    1, 0.2345678899999999, -0, -0, -0, -1.0
  };

//////// Constraint types
  char pszConTypes[] =
  {
    'G', 'E', 'E', 'E', 'E', 0
  };

////////  Total nonzeros in A matrix
  int nAnnz = 17;
////////  Column offset
  int paiAcols[] =
  {
    0,   4, 8, 10, 12, 14,
    16, 17, -1
  };

////////  Column counts
  int panAcols[] =
  {
    4, 4, 2, 2, 2, 2,
    1, -1
  };

////////  A coeff
  double padAcoef[] =
  {
    1,                   1, 1, -30, -1, -1,
    -1,                -10, 1,  -5, -1, 60,
    1,  0.2345678899999999, 1, -10, -1, -1.0
  };

///////// Row indices
  int paiArows[] =
  {
    0, 1, 2, 4, 1, 2,
    3, 4, 1, 4, 2, 4,
    3, 4, 3, 4, 4, -1
  };

//////// Lower bounds
  double padL[] =
  {
    0, 0, 0, 0, 0, 0,
    0, -1.0
  };

//////// Upper bounds
  double padU[] =
  {
    1e+030, 1e+030, 1e+030, 1e+030, 1e+030, 1e+030,
    1e+030, -1.0
  };

//////// Load LP data
  errorcode = LSloadLPData(pModel,
                           nCons, nVars, dObjSense, dObjConst, padC, padB,
                           pszConTypes, nAnnz, paiAcols, panAcols, padAcoef, paiArows, padL, padU);
  if (errorcode) return errorcode;
} // end LP/QP/CONE data




{ // begin INTEGER data
////////  Variable type
  int  errorcode     = 0;
  char pszVarTypes[] =
  {
    'C', 'C', 'C', 'C', 'C', 'C',
    'C', 0
  };

  errorcode = LSloadVarType(pModel, pszVarTypes);
  if (errorcode) return errorcode;
} // end INTEGER data




{ // begin QCP data
} // end QCP data




{ // begin CONE data
} // end CONE data




{ // begin SETS data
} // end SETS data




{ // begin SC data
} // end SC data

