NAME           NO_TITLE
*****************************************************
* REMARK: Generated by LSwriteMPSFile() routine for 
* a maximization type problem.
*
* The objective coefficients have flipped signs. 
* Interpret the objective value from the solution of
* this model accordingly.
*****************************************************
ROWS
 N       OBJ
 L  R0000000
 L  R0000001
 L  R0000002
COLUMNS
    C0000000       OBJ           -20
    C0000000  R0000000             1   R0000001             1
    C0000001       OBJ           -30
    C0000001  R0000000             2   R0000002             1
RHS
    RHS1      R0000000           120
    RHS1      R0000001            60
    RHS1      R0000002            50
BOUNDS
ENDATA
