###########################################################################
# @makefile 
#
# Linking against LINDO-API libraries on Windows Platforms.
#
# Copyright (c) 2001-2002, Lindo Systems Inc.
###########################################################################

EXAMPLE= ex_nlp3

all : $(EXAMPLE).exe

$(EXAMPLE).exe : $(EXAMPLE).cs ..\..\..\..\include\lindo.cs Form1.cs
	csc /out:$(EXAMPLE).exe $(EXAMPLE).cs ..\..\..\..\include\lindo.cs Form1.cs /platform:x86