###########################################################################
# makefile $Id$ 
#
# Linking against LINDO-API libraries on Linux/Unix Platforms.
#
# Copyright (c) 2000-2017, Lindo Systems Inc.
###########################################################################


# Specify application name

EXAMPLE=ex_nlp7

include ../makefile.unx.inc
