
/**** Generated by LSwriteSrcFile (mode=+1).
   Ready to #include from samples/c/ex_src ****/


{ // begin LP data
//////// Model sizes, objective sense and constant
  int    errorcode = 0;
  int    nCons     = 4;
  int    nVars     = 4;
  int    dObjSense = LS_MIN;
  double dObjConst = 0;
//////// Objective coefficients
  double padC[] =
  {
    -1, -2, 4, 3, -1.0
  };

//////// RHS values
  double padB[] =
  {
    5, 0, 0, 0.5, -1.0
  };

//////// Constraint types
  char pszConTypes[] =
  {
    'L', 'G', 'G', 'G', 0
  };

////////  Total nonzeros in A matrix
  int nAnnz = 8;
////////  Column offset
  int paiAcols[] =
  {
    0, 3, 6, 7, 8, -1
  };

////////  Column counts
  int panAcols[] =
  {
    3, 3, 1, 1, -1
  };

////////  A coeff
  double padAcoef[] =
  {
    1, 2, -1, 1, -1, 3,
    1, 1, -1.0
  };

///////// Row indices
  int paiArows[] =
  {
    0, 1, 2, 0, 1, 2,
    3, 3, -1
  };

//////// Lower bounds
  double padL[] =
  {
    0, 0, 1.1, 0, -1.0
  };

//////// Upper bounds
  double padU[] =
  {
    1e+030, 1e+030, 10, 1e+030, -1.0
  };

//////// Load LP data
  errorcode = LSloadLPData(pModel,
                           nCons, nVars, dObjSense, dObjConst, padC, padB,
                           pszConTypes, nAnnz, paiAcols, panAcols, padAcoef, paiArows, padL, padU);
  if (errorcode) return errorcode;
} // end LP/QP/CONE data




{ // begin INTEGER data
////////  Variable type
  int  errorcode     = 0;
  char pszVarTypes[] =
  {
    'C', 'C', 'C', 'C', 0
  };
#ifndef EXPLICT_SC
  pszVarTypes[2]='S';
#endif
  errorcode = LSloadVarType(pModel, pszVarTypes);
  if (errorcode) return errorcode;
} // end INTEGER data




{ // begin QCP data
} // end QCP data




{ // begin CONE data
} // end CONE data




{ // begin SETS data
} // end SETS data



#ifdef EXPLICT_SC
{ // begin SC data
/// SC data

  int errorcode = 0;
  int nSC       = 1;
///////// SC vars
  int paiVars[] =
  {
    2, -1
  };

///////// SC LB
  double padL[] =
  {
    1.1, -1
  };

///////// SC UB
  double padU[] =
  {
    10, -1
  };

  errorcode = LSloadSemiContData(pModel, nSC, paiVars, padL, padU);
  if (errorcode) return errorcode;
} // end SC data
#endif


