
/**** Generated by LSwriteSrcFile (mode=+1).
Ready to #include from samples/c/ex_src ****/


{ // begin core instructions
  int      errorcode      = 0;
  int      nVars          = 4;
  int      nCons          = 4;
  int      nNumbers       = 6;
  int      *paiVars       = NULL;
  double   *padVarVal     = NULL;
  double   padNumVal[]    =
  {
    0,  0.5,  2,  3,  4,  5,   -1
  };
  int      nObjs          = 1;
  int      panObjSense[]  =
  {
    LS_MIN,   -1
  };
  int      panObjLen[]    =
  {
    23,   -1
  };
  int      paiObjBeg[]    =
  {
    0,  23,   -1
  };
  int      paiConBeg[]    =
  {
    23,  33,  46,  60,  70,   -1
  };
  int      panConLen[]    =
  {
    10,  13,  14,  10,   -1
  };
  int      nInstruct      = 70;
  int      panInstruct[]  =
  {
      1070,    -101,    1063,       0,    1017,    1062,       2,    1063,       1,    1003,    1002,
      1062,       4,    1063,       2,    1003,    1001,    1062,       3,    1063,       3,    1003,
      1001,
      1070,    -101,    1063,       0,    1063,       1,    1001,    1062,       5,    1002,    1070,
      -101,    1062,       2,    1063,       0,    1003,    1063,       1,    1002,    1062,       0,
      1002,    1070,    -101,    1063,       0,    1017,    1062,       3,    1063,       1,    1003,
      1001,    1062,       0,    1002,    1070,    -101,    1063,       2,    1063,       3,    1001,
      1062,       1,    1002,   -1
  };
  char   pszVarType[]     =
  {
    'C',  'C',  'S',  'C',   -1
  };
  char   pszConType[]   =
  {
    'L',  'G',  'G',  'G',   -1
  };
  double   padLB[]   =
  {
    0,  0,  1.1,  0,   -1
  };
  double   padUB[]   =
  {
    1e+030,  1e+030,  10,  1e+030,   -1
  };


  /* Load core instructions... */
  errorcode = LSloadInstruct(pModel,nCons,nObjs,nVars,nNumbers,panObjSense,pszConType,
  	pszVarType,panInstruct,nInstruct,paiVars,padNumVal,padVarVal,paiObjBeg,panObjLen,
  	paiConBeg,panConLen,padLB,padUB);
  if (errorcode !=0) { fprintf(stdout,"\nError=%d\n",errorcode); exit(1);}

} // end core instructions


