###########################################################################
# makefile $Id$ 
#
# Linking against LINDO-API libraries on Linux/Unix Platforms.
#
# Copyright (c) 2000-2017, Lindo Systems Inc.
###########################################################################

# Choose platform and define platform specific 
include ../version.inc

EXAMPLE=ex_user3

include ../makefile.win.inc
